apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - onepassword-item.yaml
images:
  - name: akatukisora/pjserver-sys # deployment.yamlで指定したイメージ名と一致させる
    newTag: v0.0.1 # CI/CDでこのタグをビルド番号やコミットハッシュなどに置き換える
